package:
  name: libcap-ng-devel-el8-aarch64
  version: 0.7.11

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/l/libcap-ng-devel-0.7.11-1.el8.aarch64.rpm
    sha256: 7936904f9dd845e5490d9f12e85b332a0dae4bcd5d7cd87ebc10e0ce1624e681
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libcap-ng-0.7.11-1.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
  run:
    - sysroot_linux-aarch64 2.28.*
    - libcap-ng-el8-aarch64 ==0.7.11 *_0

test:
  commands:
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/include/cap-ng.h
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libcap-ng.so

about:
  home: http://people.redhat.com/sgrubb/libcap-ng
  license: LGPL-2.0-or-later
  license_family: LGPL
#  license_file: libcap-ng-copying.lib
  summary: (CDT) Header files for libcap-ng library
  description: |
    The libcap-ng-devel package contains the files needed for developing
    applications that need to use the libcap-ng library.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
