package:
  name: libselinux-el8-aarch64
  version: 2.9

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/l/libselinux-2.9-8.el8.aarch64.rpm
    sha256: 0268d7f35d7aa27f06268c464d5a351cc5f9a4d0afc59c9402e37856798d6b44
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libselinux-2.9-8.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-aarch64 2.28.*
  host:
  run:
    - sysroot_linux-aarch64 2.28.*
    - libsepol-el8-aarch64 >=2.9 *_0
    - pcre2

test:
  commands:
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libselinux.so.1

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: Public Domain
  license_family: Public-Domain
  license_file:
    - LICENSE
  summary: (CDT) SELinux library and simple utilities
  description: |
    Security-enhanced Linux is a feature of the Linux® kernel and a number of
    utilities with enhanced security functionality designed to add mandatory
    access controls to Linux.  The Security-enhanced Linux kernel contains new
    architectural components originally developed to improve the security of the
    Flask operating system. These architectural components provide general support
    for the enforcement of many kinds of mandatory access control policies,
    including those based on the concepts of Type Enforcement®, Role-based Access
    Control, and Multi-level Security.  libselinux provides an API for SELinux
    applications to get and set process and file security contexts and to obtain
    security policy decisions.  Required for any applications that use the SELinux
    API.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
