package:
  name: libtirpc-el8-aarch64
  version: 1.1.4

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/l/libtirpc-1.1.4-8.el8.aarch64.rpm
    sha256: 57d8beb5dadf3caa8624abcffd7e85f2faeccb86ede420d2e1fe06a5fadefc71
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libtirpc-1.1.4-8.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - sysroot_linux-aarch64
    - krb5
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-aarch64 2.28.*
    - krb5
  run:
    - sysroot_linux-aarch64 2.28.*
    - krb5

test:
  commands:
    - echo "it installs!"

about:
  home: http://git.linux-nfs.org/?p=steved/libtirpc.git;a=summary
  license: SISSL and BSD
  license_family: BSD
#  license_file: libtirpc-copying.lib
  summary: (CDT) Transport Independent RPC Library
  description: |
    This package contains SunLib's implementation of transport-independent
    RPC (TI-RPC) documentation.  This library forms a piece of the base of
    Open Network Computing (ONC), and is derived directly from the
    Solaris 2.3 source.

    TI-RPC is an enhanced version of TS-RPC that requires the UNIX System V
    Transport Layer Interface (TLI) or an equivalent X/Open Transport Interface
    (XTI).  TI-RPC is on-the-wire compatible with the TS-RPC, which is supported
    by almost 70 vendors on all major operating systems.  TS-RPC source code
    (RPCSRC 4.0) remains available from several internet sites.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts

