package:
  name: audit-libs-devel-el8-aarch64
  version: 3.0.7

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/a/audit-libs-devel-3.0.7-5.el8.aarch64.rpm
    sha256: f6f1aa25863d690329887d08399df4ba6a91850cd0b81e21b2a47362cc8f850a
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/a/audit-3.0.7-5.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
  run:
    - sysroot_linux-aarch64 2.28.*
    - audit-libs-el8-aarch64 ==3.0.7 *_0
    - libcap-ng-devel-el8-aarch64 >=0.7.11 *_0

test:
  commands:
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/include/libaudit.h
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/include/auparse.h
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libaudit.so
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libauparse.so

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.1-only  # LGPLv2+
  license_family: LGPL
  license_file:
    - lgpl-2.1.txt
  summary: (CDT) Header files for libaudit
  description: |
    The audit-libs-devel package contains the header files needed for developing
    applications that need to use the audit framework libraries.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
