package:
  name: pam-el8-aarch64
  version: 1.3.1

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/p/pam-1.3.1-27.el8.aarch64.rpm
    sha256: 7ee4b73e8bcbb67053fa470d6c6e4facf3b64644781f49a765682587a889be0d
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/p/pam-1.3.1-27.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - audit-libs-el8-aarch64
    - libpwquality-el8-aarch64
    - libselinux-el8-aarch64
    - libxcrypt-el8-aarch64
    - sysroot_linux-aarch64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - audit-libs-el8-aarch64 >=1.0.8 *_0
    - libpwquality-el8-aarch64 >=0.9.9 *_0
    - libselinux-el8-aarch64 >=1.33.2 *_0
    - libxcrypt-el8-aarch64 >=4.1.1 *_0
  host:
    - audit-libs-el8-aarch64 >=1.0.8 *_0
    - libpwquality-el8-aarch64 >=0.9.9 *_0
    - libselinux-el8-aarch64 >=1.33.2 *_0
    - libxcrypt-el8-aarch64 >=4.1.1 *_0
    - sysroot_linux-aarch64 2.28.*
  run:
    - audit-libs-el8-aarch64 >=1.0.8 *_0
    - libpwquality-el8-aarch64 >=0.9.9 *_0
    - libselinux-el8-aarch64 >=1.33.2 *_0
    - libxcrypt-el8-aarch64 >=4.1.1 *_0
    - sysroot_linux-aarch64 2.28.*
test:
  commands:
    - echo "it installs!"

about:
  home: http://www.linux-pam.org/
  license: BSD and GPLv2+
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/licenses/pam/Copyright
  summary: (CDT) An extensible library which provides authentication for applications
  description: |
    PAM (Pluggable Authentication Modules) is a system security tool that allows
    system administrators to set authentication policy without having to recompile
    programs that handle authentication.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts

