package:
  name: cracklib-dicts-el8-aarch64
  version: 2.9.6

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/c/cracklib-dicts-2.9.6-15.el8.aarch64.rpm
    sha256: 3de7f7a185d72b768965b67eb00290f3cf4a27ea169009fbaab5a4cd0f39ab9c
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/PowerTools/Source/Packages/cracklib-2.9.6-15.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
  run:
    - sysroot_linux-aarch64 2.28.*
    - cracklib-el8-aarch64 ==2.9.6 *_0

test:
  commands:
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/cracklib_dict.pwd

about:
  home: http://sourceforge.net/projects/cracklib/
  # The license isn't maintained in the code base but the original
  # development site, https://sourceforge.net/projects/cracklib/,
  # suggests LGPL-2.0
  license: LGPL-2.0-only  # LGPL-2.0-or-later
  license_family: LGPL
  license_file:
    - LGPL-2.0-only
  summary: (CDT) The standard CrackLib dictionaries
  description: |
    The cracklib-dicts package includes the CrackLib dictionaries. CrackLib will
    need to use the dictionary appropriate to your system, which is normally put
    in /usr/share/dict/words. Cracklib-dicts also contains the utilities necessary
    for the creation of new dictionaries.  If you are installing CrackLib, you
    should also install cracklib-dicts.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
