package:
  name: libpwquality-devel-el8-aarch64
  version: 1.4.4

source:
  - url: https://vault.almalinux.org/8.9/PowerTools/aarch64/os/Packages/libpwquality-devel-1.4.4-6.el8.aarch64.rpm
    sha256: 691721ee59cde205c73cff769666b4cc4e256d8d7605c03a0d1d4b362d1432c6
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libpwquality-1.4.4-6.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libpwquality-el8-aarch64 ==1.4.4 *_0
  host:
    - libpwquality-el8-aarch64 ==1.4.4 *_0
    - sysroot_linux-aarch64 2.28.*
  run:
    - libpwquality-el8-aarch64 ==1.4.4 *_0
    - sysroot_linux-aarch64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/libpwquality/libpwquality/
  license: BSD or GPLv2+
  license_family: GPL2
#  license_file: libpwquality-copying
  summary: (CDT) Support for development of applications using the libpwquality library
  description: |
    Files needed for development of applications using the libpwquality library.
    See the pwquality.h header file for the API.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts

