package:
  name: libpwquality-el8-aarch64
  version: 1.4.4

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/l/libpwquality-1.4.4-6.el8.aarch64.rpm
    sha256: e490223a9b8a3c494f190487d10290115b60bc42cced7bf772c062edad08abed
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libpwquality-1.4.4-6.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-aarch64 2.28.*
  host:
  run:
    - sysroot_linux-aarch64 2.28.*
    - cracklib-el8-aarch64 >=2.8 *_0
    - cracklib-dicts-el8-aarch64 >=2.8 *_0
    - pam-el8-aarch64 >=1.3.1 *_0  # [with_pam]

test:
  commands:
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libpwquality.so.1
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libpwquality.so.1.0.2

about:
  home: https://github.com/libpwquality/libpwquality/
  license: BSD-3-Clause or GPL-2.0-only  # BSD or GPLv2+
  license_family: GPL2
  license_file:
    - COPYING
  summary: "(CDT) A library for password generation and password quality checking"
  description: |
        This is a library for password quality checks and generation of random
        passwords that pass the checks. This library uses the cracklib and cracklib
        dictionaries to perform some of the checks.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
