package:
  name: libsepol-devel-el8-aarch64
  version: 2.9

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/l/libsepol-devel-2.9-3.el8.aarch64.rpm
    sha256: 317705b5f8b8a267fa79aa17d581fd13d8d7b40cf94a538d7b9a9dfef9394933
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libsepol-2.9-3.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libsepol-el8-aarch64 ==2.9 *_0
  host:
    - libsepol-el8-aarch64 ==2.9 *_0
    - sysroot_linux-aarch64 2.28.*
  run:
    - libsepol-el8-aarch64 ==2.9 *_0
    - sysroot_linux-aarch64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: LGPL-2.0-or-later
  license_family: LGPL
#  license_file: libsepol-license
  summary: (CDT) Header files and libraries used to build policy manipulation tools
  description: |
    The libsepol-devel package contains the libraries and header files needed for
    developing applications that manipulate binary policies.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts

