package:
  name: libxcrypt-devel-el8-aarch64
  version: 4.1.1

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/l/libxcrypt-devel-4.1.1-6.el8.aarch64.rpm
    sha256: da9307e19104245a81d4174b81135d92376dfd15397383245532001838a2de19
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libxcrypt-4.1.1-6.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
  run:
    - sysroot_linux-aarch64 2.28.*
    - libxcrypt-el8-aarch64 ==4.1.1 *_0

test:
  requires:
    - pkg-config
  commands:
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/include/crypt.h
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/lib64/libcrypt.so
    - export PKG_CONFIG_PATH=${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/pkgconfig
    - pkg-config --cflags libcrypt
    - pkg-config --cflags libxcrypt

about:
  home: https://github.com/besser82/libxcrypt
  license: LGPL-2.0-or-later AND BSD AND Public Domain
  license_family: LGPL
#  license_file: libxcrypt-copying.lib
  summary: (CDT) Development files for libxcrypt
  description: |
    The libxcrypt-devel package contains libraries and header files for
    developing applications that use libxcrypt.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
