package:
  name: cracklib-el8-aarch64
  version: 2.9.6

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/c/cracklib-2.9.6-15.el8.aarch64.rpm
    sha256: 7850e3b197ca42eb625e524573e38e0bf3366b8da69b9c5cd08efdbb57439994
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/c/cracklib-2.9.6-15.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - sysroot_linux-aarch64
    - zlib
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-aarch64 2.28.*
    - zlib
  run:
    - sysroot_linux-aarch64 2.28.*
    - zlib

test:
  commands:
    - echo "it installs!"

about:
  home: http://sourceforge.net/projects/cracklib/
  license: LGPL-2.0-or-later
  license_family: LGPL
#  license_file: cracklib-copying.lib
  summary: (CDT) A password-checking library
  description: |
    CrackLib tests passwords to determine whether they match certain security-
    oriented characteristics, with the purpose of stopping users from choosing
    passwords that are easy to guess. CrackLib performs several tests on
    passwords: it tries to generate words from a username and gecos entry and
    checks those words against the password; it checks for simplistic patterns in
    passwords; and it checks for the password in a dictionary.  CrackLib is
    actually a library containing a particular C function which is used to check
    the password, as well as other C functions. CrackLib is not a replacement for
    a passwd program; it must be used in conjunction with an existing passwd
    program.  Install the cracklib package if you need a program to check users'
    passwords to see if they are at least minimally secure. If you install
    CrackLib, you will also want to install the cracklib-dicts package.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts

