package:
  name: kmod-libs-el8-aarch64
  version: 25

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/k/kmod-libs-25-19.el8.aarch64.rpm
    sha256: 754c6d1db5fbd7daee3cbcea722a71971595c45d09cd3346ccef0494ea2e37d0
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/k/kmod-25-19.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - sysroot_linux-aarch64
    - libxcrypt-el8-aarch64
    - openssl
    - xz
    - zlib
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-aarch64 2.28.*
    - libgcc-ng
    - libxcrypt-el8-aarch64 >=4.1.1 *_0
    - openssl 1  # libcrypto.so.1.1
    - xz
    - zlib
  run:
    - sysroot_linux-aarch64 2.28.*
    - libgcc-ng
    - libxcrypt-el8-aarch64 >=4.1.1 *_0
    - openssl 1  # libcrypto.so.1.1
    - xz
    - zlib

test:
  commands:
    - echo "it installs!"

about:
  home: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary
  license: LGPL-2.0-or-later
  license_family: LGPL
#  license_file: kmod-copying
  summary: (CDT) Libraries to handle kernel module loading and unloading
  description: |
    The kmod-libs package provides runtime libraries for any application that
    wishes to load or unload Linux kernel modules from the running system.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts

