package:
  name: libcap-ng-el8-aarch64
  version: 0.7.11

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/l/libcap-ng-0.7.11-1.el8.aarch64.rpm
    sha256: ca0c5cd3a6ff1505113b2b220844603077d282b81f790a205e7d23ab6cf68a61
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libcap-ng-0.7.11-1.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-aarch64 2.28.*
  host:
  run:
    - sysroot_linux-aarch64 2.28.*

test:
  commands:
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/lib64/libcap-ng.so.0
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/lib64/libcap-ng.so.0.0.0

about:
  home: http://people.redhat.com/sgrubb/libcap-ng
  license: LGPL-2.1-only  # LGPLv2+
  license_family: LGPL
  license_file:
    - COPYING.LIB
  summary: (CDT) An alternate posix capabilities library
  description: |
    Libcap-ng is a library that makes using posix capabilities easier
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
