package:
  name: kmod-devel-el8-aarch64
  version: 25

source:
  - url: https://vault.almalinux.org/8.9/PowerTools/aarch64/os/Packages/kmod-devel-25-19.el8.aarch64.rpm
    sha256: 1b949bb00733d021379e8f4e293dfb4cfe08efbc7ddf1b46aaeb4dcfb34da9ff
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/k/kmod-25-19.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
  run:
    - sysroot_linux-aarch64 2.28.*
    - kmod-libs-el8-aarch64 ==25 *_0
    - libxcrypt-devel-el8-aarch64 >=4.1.1 *_0

test:
  requires:
    - pkg-config
  commands:
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/include/libkmod.h
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libkmod.so
    - export PKG_CONFIG_PATH=${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/pkgconfig
    - pkg-config --cflags libkmod

about:
  home: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary
  license: LGPL-2.1-only  # LGPLv2+
  license_family: GPL2
  license_file:
    - COPYING
  summary: (CDT) Header files for kmod development
  description: |
    The kmod-devel package provides header files used for development of
    applications that wish to load or unload Linux kernel modules.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
