package:
  name: audit-libs-el8-aarch64
  version: 3.0.7

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/aarch64/os/Packages/a/audit-libs-3.0.7-5.el8.aarch64.rpm
    sha256: fba8d166691c36c56b7eb475629a3c91c22b58663e55a0fcf944c93f26ba7083
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/a/audit-3.0.7-5.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and aarch64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-aarch64 2.28.*
  host:
  run:
    - sysroot_linux-aarch64 2.28.*
    - libcap-ng-el8-aarch64 >=0.7.11 *_0

test:
  commands:
    - test ! -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libaudit.so
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libaudit.so.1
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libaudit.so.1.0.0
    - test ! -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libauparse.so
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libauparse.so.0
    - test -f ${PREFIX}/aarch64-conda_el8-linux-gnu/sysroot/usr/lib64/libauparse.so.0.0.0

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.1-only  # LGPLv2+
  license_family: LGPL
  license_file:
    - lgpl-2.1.txt
  summary: (CDT) Dynamic library for libaudit
  description: |
    The audit-libs package contains the dynamic libraries needed for applications
    to use the audit framework.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
